---
  - name: Teesting diffeerent things
    hosts: all
    become: true
    vars_files:
      - vars.yml



    tasks:

      - name: checking is port available
        ansible.builtin.wait_for: 
          host: "{{ server1 }}"
          port: 22
        delegate_to: localhost
        register: result

      - name: Display the output from the node server
        debug:
          var: result.stdout_lines